### ISSUE TITLE
Which error-checking Ada mode is measured

### ISSUE THREAD

**Issue by vporton** [nbraud/benchmarksgame#1]
At http://benchmarksgame.alioth.debian.org/u64q/ada.html and http://benchmarksgame.alioth.debian.org/u64q/compare.php?lang=gnat&lang2=gpp it should be explicitly stated whether GNAT is run in error checking mode (that is throws exceptions if an array is out-of-bounds, an integer overflows, etc.)

My suggestion is that GNAT should be measured with error checking off, because it is compared with C or C++ which are always not in error checking mode.

**Comment by nbraud** [comment]
Please do not report issues here.  This is not the right place, only an unofficial Git mirror.
